[project]
name = "stock-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yeshwanth", email = "yedpuganti@fortinet.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
    "streamlit>=1.63.0",
    "yfinance>=1.7.0",
]

[project.scripts]
stock-monitor = "stock_monitor:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
